/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PaginaPublicaRouteImport } from './routes/pagina-publica'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding-preview'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DemoPerfilRouteImport } from './routes/demo-perfil'
import { Route as DemoPaginaPublicaRouteImport } from './routes/demo-pagina-publica'
import { Route as DemoPagamentoRouteImport } from './routes/demo-pagamento'
import { Route as DemoPacientesRouteImport } from './routes/demo-pacientes'
import { Route as DemoFinanceiroRouteImport } from './routes/demo-financeiro'
import { Route as DemoDashboardRouteImport } from './routes/demo-dashboard'
import { Route as DemoAgendaRouteImport } from './routes/demo-agenda'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaPublicaRoute = PaginaPublicaRouteImport.update({
  id: '/pagina-publica',
  path: '/pagina-publica',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/onboarding-preview',
  path: '/onboarding-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPerfilRoute = DemoPerfilRouteImport.update({
  id: '/demo-perfil',
  path: '/demo-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPaginaPublicaRoute = DemoPaginaPublicaRouteImport.update({
  id: '/demo-pagina-publica',
  path: '/demo-pagina-publica',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPagamentoRoute = DemoPagamentoRouteImport.update({
  id: '/demo-pagamento',
  path: '/demo-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPacientesRoute = DemoPacientesRouteImport.update({
  id: '/demo-pacientes',
  path: '/demo-pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/demo-financeiro',
  path: '/demo-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo-dashboard',
  path: '/demo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/demo-agenda',
  path: '/demo-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-agenda': typeof DemoAgendaRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/demo-financeiro': typeof DemoFinanceiroRoute
  '/demo-pacientes': typeof DemoPacientesRoute
  '/demo-pagamento': typeof DemoPagamentoRoute
  '/demo-pagina-publica': typeof DemoPaginaPublicaRoute
  '/demo-perfil': typeof DemoPerfilRoute
  '/financeiro': typeof FinanceiroRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/pagina-publica': typeof PaginaPublicaRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-agenda': typeof DemoAgendaRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/demo-financeiro': typeof DemoFinanceiroRoute
  '/demo-pacientes': typeof DemoPacientesRoute
  '/demo-pagamento': typeof DemoPagamentoRoute
  '/demo-pagina-publica': typeof DemoPaginaPublicaRoute
  '/demo-perfil': typeof DemoPerfilRoute
  '/financeiro': typeof FinanceiroRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/pagina-publica': typeof PaginaPublicaRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-agenda': typeof DemoAgendaRoute
  '/demo-dashboard': typeof DemoDashboardRoute
  '/demo-financeiro': typeof DemoFinanceiroRoute
  '/demo-pacientes': typeof DemoPacientesRoute
  '/demo-pagamento': typeof DemoPagamentoRoute
  '/demo-pagina-publica': typeof DemoPaginaPublicaRoute
  '/demo-perfil': typeof DemoPerfilRoute
  '/financeiro': typeof FinanceiroRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/pagina-publica': typeof PaginaPublicaRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/dashboard'
    | '/demo'
    | '/demo-agenda'
    | '/demo-dashboard'
    | '/demo-financeiro'
    | '/demo-pacientes'
    | '/demo-pagamento'
    | '/demo-pagina-publica'
    | '/demo-perfil'
    | '/financeiro'
    | '/onboarding'
    | '/onboarding-preview'
    | '/pagina-publica'
    | '/patients'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/dashboard'
    | '/demo'
    | '/demo-agenda'
    | '/demo-dashboard'
    | '/demo-financeiro'
    | '/demo-pacientes'
    | '/demo-pagamento'
    | '/demo-pagina-publica'
    | '/demo-perfil'
    | '/financeiro'
    | '/onboarding'
    | '/onboarding-preview'
    | '/pagina-publica'
    | '/patients'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/dashboard'
    | '/demo'
    | '/demo-agenda'
    | '/demo-dashboard'
    | '/demo-financeiro'
    | '/demo-pacientes'
    | '/demo-pagamento'
    | '/demo-pagina-publica'
    | '/demo-perfil'
    | '/financeiro'
    | '/onboarding'
    | '/onboarding-preview'
    | '/pagina-publica'
    | '/patients'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoPacientesRoute: typeof DemoPacientesRoute
  DemoPagamentoRoute: typeof DemoPagamentoRoute
  DemoPaginaPublicaRoute: typeof DemoPaginaPublicaRoute
  DemoPerfilRoute: typeof DemoPerfilRoute
  FinanceiroRoute: typeof FinanceiroRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  PaginaPublicaRoute: typeof PaginaPublicaRoute
  PatientsRoute: typeof PatientsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagina-publica': {
      id: '/pagina-publica'
      path: '/pagina-publica'
      fullPath: '/pagina-publica'
      preLoaderRoute: typeof PaginaPublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-preview': {
      id: '/onboarding-preview'
      path: '/onboarding-preview'
      fullPath: '/onboarding-preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-perfil': {
      id: '/demo-perfil'
      path: '/demo-perfil'
      fullPath: '/demo-perfil'
      preLoaderRoute: typeof DemoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-pagina-publica': {
      id: '/demo-pagina-publica'
      path: '/demo-pagina-publica'
      fullPath: '/demo-pagina-publica'
      preLoaderRoute: typeof DemoPaginaPublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-pagamento': {
      id: '/demo-pagamento'
      path: '/demo-pagamento'
      fullPath: '/demo-pagamento'
      preLoaderRoute: typeof DemoPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-pacientes': {
      id: '/demo-pacientes'
      path: '/demo-pacientes'
      fullPath: '/demo-pacientes'
      preLoaderRoute: typeof DemoPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-financeiro': {
      id: '/demo-financeiro'
      path: '/demo-financeiro'
      fullPath: '/demo-financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-dashboard': {
      id: '/demo-dashboard'
      path: '/demo-dashboard'
      fullPath: '/demo-dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-agenda': {
      id: '/demo-agenda'
      path: '/demo-agenda'
      fullPath: '/demo-agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DemoAgendaRoute: DemoAgendaRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoPacientesRoute: DemoPacientesRoute,
  DemoPagamentoRoute: DemoPagamentoRoute,
  DemoPaginaPublicaRoute: DemoPaginaPublicaRoute,
  DemoPerfilRoute: DemoPerfilRoute,
  FinanceiroRoute: FinanceiroRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  PaginaPublicaRoute: PaginaPublicaRoute,
  PatientsRoute: PatientsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
